language: cpp

services: mongodb

compiler:
  - clang

install:
  - "pip install -r requirements.txt"
  - "python setup.py install"
  - "npm install -g grunt grunt-cli"
  - "npm install"
  - "grunt init"
  - "grunt"

before_script:
  - mkdir _build
  - cd _build

script:
  - cmake ..
  - make
  - ctest -V
